### ISSUE TITLE
Common DataSource Example In Charts Not Working

### ISSUE THREAD

**Issue by tru-koto** [syncfusion/ej2-angular-docs#2]
https://ej2.syncfusion.com/angular/documentation/chart/working-with-data/#common-datasource

**Comment by Arunsanthoshh** [comment]
Hi Team,   
  
We have validated your query. We have logged a UG task regarding this and the fix will be available in our upcoming Volume 1 release which will be scheduled to be rolled out on or before the end of March 2021. I have prepared the stackblitz sample below with a fixed code snippet of the reported UG link. Until then you can use the below sample. 
  
Stackblitz - https://stackblitz.com/edit/angular-d37sjy?file=app.component.ts 
 
Thanks,  
Arun

**Comment by tru-koto** [comment]
@Arunsanthoshh - Ok. 

Ideally the fix allows a developer to use ngForOf with the <e-series> element in combination with the dataSource being bound  on the <ejs-chart> element.

This would allow much more dynamic control for a developer. I'd imagine my life would be easier in the following example if there was the ability to bind to a common dataSource.

https://www.syncfusion.com/forums/162312/column-chart-ngforof-e-series-confusion

**Comment by DurgaGopalakrishnan** [comment]
Hi Team,  
  
We have modified the documentation based on your requirement. And it is published online. Please find the link below.  
  
UG Link: https://ej2.syncfusion.com/angular/documentation/chart/working-with-data/#common-datasource

Let us know if you need further assistance on this.  
  
Regards,  
Durga G
