### ISSUE TITLE
tooltip attributes not working

### ISSUE THREAD

**Issue by ahmedask1** [syncfusion/ej2-angular-docs#6]
0

I am working on a tooltip with ejs lineargauge, I have checked all the attributes whether in the documentation or in the internal classes, but none of the attributes is working. I want to change the content ; text color and background color

This is the part of the HTML code:

anycomponent.component.html

<ejs-lineargauge #axesActivite (tooltipRender)='tooltipRender($event)' [allowMargin]="false"
[axes]='axesAct'[tooltip]="tooltip"
This is the part of ts file anycomponent.component.ts After export class....

 tooltip: Object = {
    type: ['Range'],
    enable: true,
    position: 'Center',
    fill: '#e5bcbc',
None of the attributes is working only Range and enable are working, all the others are not working whether fill or position.

**Comment by sabari-senthamaraikannan** [comment]
Hi,

In the provided code snippet, you have set the "**type**" property to "**Range**" in the "**tooltipSettings**" property, but other properties of the "**tooltipSettings**" such as "position", "format" and "fill" are used to render the **pointer's tooltip and not the range**. So, you are facing the reported scenario.

To customize the tooltip for the pointers, use the direct properties in the "**tooltipSettings**". And, to customize the tooltip for the ranges, use the properties in the "**rangeSettings**", which lies inside the "**tooltipSettings**". Please find the code snippet below for your reference.

**Code snippet**:
`public Tooltip: Object = {`
`    enable: true,`
 `   type: ['Pointer', 'Range'],`
`    position: 'Center',`
 `   fill: '#e5bcbc',`
`    format: 'Pointer Value: {value}',`
`    textStyle: {`
 `     color: 'black',`
`    },`
 `   rangeSettings: {`
`      format: 'Begin: {start} <br> End: {end}',`
`      position: 'Center',`
 `     fill: 'blue',`
`      textStyle: {`
`        color: 'black',`
`      },`
`    }`

**NOTE**: In the above code, “**type**” property has two values. “**Pointer**” is used to render tooltip for the pointer and “**Range**” is used to render tooltip for the ranges.

We have created a sample to demonstrate the same and it can be found from the below link.

[https://stackblitz.com/edit/angular-1bdclt?file=app.component.ts](https://stackblitz.com/edit/angular-1bdclt?file=app.component.ts)

Please let us know if you have any concerns.

Regards,
Sabari Anand.
