### ISSUE TITLE
Theme Studio returns 504 when attempting to download theme

### ISSUE THREAD

**Issue by shelleyeti** [syncfusion/ej2-angular-docs#9]
It appears to time out when trying to download the theme.

**Comment by JamunaSundaramSF3699** [comment]
The theme studio issue has been resolved and refreshed on the live server. You can find the below documentation for reference.

https://ej2.syncfusion.com/themestudio/?theme=material-dark

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for weeks. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
